"use client";
import type { Metadata } from "next";
import {
  Button,
  Modal,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalHeader,
  ModalOverlay,
  Text,
} from "@chakra-ui/react";
import { User } from "@/app/types/users";
import { useHooks } from "./hooks";

export function Users({
  users,
}: Readonly<{
  users: User[];
}>) {
  const { openModal, closeModal, isOpen, isPending, createDirectMessageChat } =
    useHooks();

  return (
    <>
      {users.map(({ id, userName }) => {
        return (
          <Button
            key={id}
            w="100%"
            borderBottom="1px solid gray"
            alignItems="start"
            flexDirection="column"
            onClick={() => openModal(id)}
          >
            <Text>{userName}</Text>
          </Button>
        );
      })}
      <Modal isOpen={isOpen} onClose={closeModal} isCentered>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Start Chat?</ModalHeader>
          <ModalCloseButton />
          <ModalFooter>
            <Button
              colorScheme="blue"
              mr={3}
              onClick={createDirectMessageChat}
              isLoading={isPending}
            >
              Yes
            </Button>
          </ModalFooter>
        </ModalContent>
      </Modal>
    </>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
