import type { Metadata } from "next";
import { Box, Text, VStack } from "@chakra-ui/react";
import { DmChannel, User } from "../types/users";
import { SIDEBAR_WIDTH } from "../constants";
import { Users } from "./components/users";
import { getTokenAction } from "./actions/getTokenAction";
import { DirectMessageChannels } from "./components/direct-message-channels";

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  try {
    const users = await fetch("http://localhost:8080/api/users");
    const usersJson: User[] = await users.json();

    const { token } = await getTokenAction();
    const directMessageChannels = await fetch(
      "http://localhost:8080/api/direct-message-channels",
      {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
      }
    );
    const directMessageChannelsJson: DmChannel[] =
      await directMessageChannels.json();

    return (
      <Box p="24px">
        <Box
          position="fixed"
          w={`${SIDEBAR_WIDTH}px`}
          borderRight="1px solid gray"
          h="100dvh"
        >
          <VStack gap="24px" alignItems="start" mb="24px">
            <Text fontWeight={700}>Users</Text>
            <Users users={usersJson} />
          </VStack>
          <VStack gap="24px" alignItems="start">
            <Text fontWeight={700}>Direct Messages</Text>
            <DirectMessageChannels
              directMessageChannels={directMessageChannelsJson}
            />
          </VStack>
        </Box>
        <Box ml={`${SIDEBAR_WIDTH}px`} w={`calc(100dvw - ${SIDEBAR_WIDTH}px)`}>
          {children}
        </Box>
      </Box>
    );
  } catch (error) {
    console.error(error);
    return <Text>Failed to fetch data</Text>;
  }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
