"use client";
import type { Metadata } from "next";
import { Button, Text } from "@chakra-ui/react";
import { DmChannel } from "@/app/types/users";
import { useHooks } from "./hooks";

export function DirectMessageChannels({
  directMessageChannels,
}: Readonly<{
  directMessageChannels: DmChannel[];
}>) {
  useHooks();
  return (
    <>
      {directMessageChannels.map(({ id, userName }) => {
        return (
          <Button
            key={id}
            w="100%"
            borderBottom="1px solid gray"
            alignItems="start"
            flexDirection="column"
          >
            <Text>{userName}</Text>
          </Button>
        );
      })}
    </>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
